version: "3"
services:
    angular_cli:
        container_name: dotnet-sdk
        build:
            context: ./docker/dotnet-sdk
                # volumes
        volumes:
            - ".:/workspace"
        ports:
            - 5000:5000
            - 5001:5001
        # command: >
        #     bash
        stdin_open: true # docker run -i
        tty: true # docker run -t