// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WeatherApi.Database;

#nullable disable

namespace WeatherApi.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211204175250_Data")]
    partial class Data
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WeatherApi.Database.Entities.Summary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Summaries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Freezing"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Bracing"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Chilly"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Cool"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Mild"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Warm"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Balmy"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Hot"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Sweltering"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Scorching"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
